export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';
export const GET_INVOICE_START = 'GET_INVOICE_START';

export const DELETE_INVOICE_START = 'DELETE_INVOICE_START';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL';

export const ADD_INVOICE_START = 'ADD_INVOICE_START';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAIL = 'ADD_INVOICE_FAIL';

export const EDIT_INVOICE_START = 'EDIT_INVOICE_START';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_FAIL = 'EDIT_INVOICE_FAIL';

export const VIEW_INVOICE_START = 'VIEW_INVOICE_START';
export const VIEW_INVOICE_SUCCESS = 'VIEW_INVOICE_SUCCESS';
export const VIEW_INVOICE_FAIL = 'VIEW_INVOICE_FAIL';

export const GET_ORDER_START = 'GET_ORDER_START';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';
